### ISSUE TITLE
Run files according to the ordering in gorgon.json

### ISSUE THREAD

**Issue by arturopie** [nulogy/Gorgon#72]
Use ordering of globs in "files" property of gorgon.json as first precedence and runtime as second precedence. This will allow users override runtime ordering if they need to (for example, to run transient files first or to run test of a specific environment first). Here is an example:

 Given we have the following in gorgon.json
 ```
 ...
 "files": [
     "spec/file1_spec.rb",
     "spec/**/*_spec.rb",
     "test/**/*_test.rb"
   ],
 ...
 ```

 Gorgon will run files in the following order:
 1. spec/file1_spec.rb
 2. spec/**/*_spec.rb in runtime order
 3. test/**/*_test.rb in runtime order

**Comment by JonErikDSuero** [comment]
@arturopie I created a pull request https://github.com/nulogy/Gorgon/pull/73/files.
Please code review.
Thanks
